#!/usr/bin/env bash

# Services
pgrep -x sxhkd > /dev/null || sxhkd &

# This is where the magic happens
polybar-bspwm &

#### MONITORS ####
primary=false
for monitor in $(bspc query -M)
do
    # 5 workspaces on the primary monitor, and 2 on the secondary
    if [ $primary == false ]; then
      bspc monitor $monitor -d 1 2 3 4 5 6 7 8 9
    else
      bspc monitor $monitor -d 1 2 3
    fi
    #polybar hidden when fullscreen for vlc, youtube, mpv ...
    xdo below -t $(xdo id -n root) $(xdo id -a polybar-mainbar_$monitor)
    primary=true
done

bspc config automatic_scheme              alternate
bspc config border_width                  1
bspc config window_gap                    20
bspc config top_padding                   28
bspc config bottom_padding                0
bspc config left_padding                  0
bspc config right_padding                 0
bspc config single_monocle                false
bspc config split_ratio                   0.6
bspc config borderless_monocle            true
bspc config gapless_monocle               true
bspc config focus_follows_pointer         true
bspc config remove_disabled_monitors      true
bspc config merge_overlapping_monitors    true
bspc config pointer_modifier              mod4
bspc config pointer_action1               move
bspc config pointer_action2               resize_corner
bspc config pointer_action3               resize_side

#### BSPWM coloring ####
# bspc config normal_border_color         "#424242"
# bspc config active_border_color	        "#806080"
# bspc config focused_border_color	      "#503050"
# bspc config presel_feedback_color	      "#75617b"

# Dracula
bspc config normal_border_color     "#44475a"
bspc config active_border_color     "#bd93f9"
bspc config focused_border_color    "#ff79c6"
bspc config presel_feedback_color   "#6272a4"

bspc rule -a Screenkey manage=off

# Primary Monitor
bspc rule -a XIVLauncher.Core desktop='^1:^4' state=floating center=on border=off
bspc rule -a ffxiv_dx11.exe:ffxiv_dx11.exe desktop='^1:^4'
bspc rule -a obs:obs desktop='^1:^9'

# Floaters
bspc rule -a Galculator state=floating center=on border=off
bspc rule -a Blender state=floating center=on border=off
bspc rule -a scratchpad sticky=on state=floating center=on
bspc rule -a Bitwarden state=floating center=on desktop='^1:^9'

# Wine Apps
bspc rule -a daz3dim.exe state=floating follow=on center=on desktop='^1:^7'
bspc rule -a dazstudio.exe follow=on desktop='^1:^7'

# pgrep -f swallow.py > /dev/null || ~/.config/bspwm/scripts/swallow.py &
# pgrep -f automatic_tab.py > /dev/null || ~/.config/bspwm/scripts/automatic_tab.py &
