#!/usr/bin/env bash

# Services
pgrep -x sxhkd > /dev/null || sxhkd &
pgrep -x ntfd > /dev/null || ntfd &
pgrep -x openrgb > /dev/null || openrgb --server &
pgrep -x streamdeck > /dev/null || streamdeck -n &

picom -b &
polybar-bspwm &
/usr/bin/dunst &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

# Wallpaper
feh --no-fehbg --bg-fill --no-xinerama ${HOME}/.config/wallpaper.jpg &

# Screen lock
xautolock -locker slock -nowlocker slock -time 30 -secure &
xsetroot -cursor_name left_ptr &

#### MONITORS ####
primary=false
for monitor in $(bspc query -M)
do
    # 5 workspaces on the primary monitor, and 2 on the secondary
    if [ $primary == false ]; then
      bspc monitor $monitor -d 1 2 3 4 5
    else
      bspc monitor $monitor -d 1 2
    fi
    #polybar hidden when fullscreen for vlc, youtube, mpv ...
    xdo below -t $(xdo id -n root) $(xdo id -a polybar-mainbar_$monitor)
    primary=true
done

bspc config border_width                  2
bspc config window_gap                    30
bspc config top_padding                   20
bspc config bottom_padding                0
bspc config left_padding                  0
bspc config right_padding                 0
bspc config single_monocle                false
bspc config click_to_focus                true
bspc config split_ratio                   0.60
bspc config borderless_monocle            true
bspc config gapless_monocle               true
bspc config focus_by_distance             true
bspc config focus_follows_pointer         true
bspc config history_aware_focus           true
bspc config remove_disabled_monitors      true
bspc config merge_overlapping_monitors    true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

#### BSPWM coloring ####
bspc config normal_border_color         "#556a7d"
bspc config active_border_color	        "#E1C0FA"
bspc config focused_border_color	      "#97BEDC"
bspc config presel_feedback_color	      "#75617b"
bspc config urgent_border_color 	      "#CD5C5C"

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# Pre-define some window locations
# Browsers on workspace 1:2
bspc rule -a Google-chrome:google-chrome -o node=@^1:^2:/1
bspc rule -a Vivaldi-stable:vivaldi-stable -o node=@^1:^2:/2
bspc rule -a Google-chrome:crx_pkooggnaalmfkidjmlhoelhdllpphaga -o node=@^1:^2:/2/2

# Games on 1:4
bspc rule -a ffxiv_dx11.exe:ffxiv_dx11.exe -o node=@^1:^4:/2

# OBS Studio on 1:5
bspc rule -a obs:obs -o node=@^1:^5:/

# Chats on the second monitor
bspc rule -a Slack:slack -o node=@^2:^1:/1
bspc rule -a Google-chrome:crx_cifhbcnohmdccbgoicgdjpfamggdegmo -o node=@^2:^1:/2
bspc rule -a discord:discord -o node=@^2:^2:/
bspc rule -a Element:element -o node=@^2:^2:/2
